theme: jekyll-theme-minimal
title: fromatogra
description: Software and mathematics
markdown: kramdown
google_analytics: UA-109740765-1
collections:
  math:
    output: true
    permalink: /:collection/:name
